# // THIS CODE IS MY OWN WORK, IT WAS WRITTEN WITHOUT CONSULTING
# // A TUTOR OR CODE WRITTEN BY OTHER STUDENTS - LAURA NEFF

all: mysh

mysh: mysh.c tokens.c
	gcc -ggdb -std=gnu99 -Wformat=0 -o mysh mysh.c tokens.c

clean:
	rm mysh